artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/blob/master/samsumdata.zip
  unzip_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/samsumdata.zip