artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: C:\Users\admin\OneDrive\Desktop\Machine-learning A-Z\deep learning\Text_summarizer_project\summarizer-data.zip
  unzip_dir: artifacts/data_ingestion 
